### ISSUE TITLE
RMAN recovery after issue/problems

### ISSUE THREAD

**Issue by jjjeroenski** [sergiotocalini/zabora#3]
Trigger after "Oracle: RMAN has problems" keeps triggerd and is not resolved.

for example: There was an issue last weekend, issue resolved and already 2 new RMAN cycled finished completed without errors.

If I manually run the SQL : "db_rman.sql" everything is OK now, output : 0 like expected.
But in zabbix the problem is still there, also latest data shows only the timestamp of the last error happening.

Is this normal behavior and/or how do you handle this?

**Comment by sergiotocalini** [comment]
Hi @jjjeroenski 
Indeed, if I remember correctly in the zabbix template the check is running once a day and it will check if in the last 24 hours there is an issue it will actived the trigger. It should be solved by the next day that the issue is solved. You can change this behaviour if you would like to but this will need to be on your own zabbix template configuration ;)
Best,
Sergio

**Comment by jjjeroenski** [comment]
ok thanks for your time and work in this scripts!
